services:
  primary:
    image: bitnami/postgresql@sha256:7a695433df7728a4efa0c66310f4e9e71a37f3fbbc1bb179b8308896dff40a6c     #18.3
    container_name: taxi_postgres_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replicator
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: taxi_db
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: on
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
    volumes:
      - primary_data:/bitnami/postgresql

  replica:
    image: bitnami/postgresql@sha256:7a695433df7728a4efa0c66310f4e9e71a37f3fbbc1bb179b8308896dff40a6c
    container_name: taxi_postgres_replica
    ports:
      - "5433:5432"
    depends_on:
      - primary
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replicator
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_HOST: primary
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: root
    volumes:
      - replica_data:/bitnami/postgresql

  mongodb:
    image: mongo:8.2
    container_name: taxi_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis-master:
    image: redis:8.6
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --replica-announce-ip redis-master --replica-announce-port 6379
    volumes:
      - redis_master_data:/data

  redis-replica:
    image: redis:8.6
    container_name: redis-replica
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    command: redis-server --replicaof redis-master 6379 --replica-announce-ip redis-replica --replica-announce-port 6379
    volumes:
      - redis_replica_data:/data

  redis-sentinel:
    image: redis:8.6
    container_name: redis-sentinel
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-replica
    command: >
      sh -c "echo 'port 26379' > /tmp/sentinel.conf &&
      echo 'dir /tmp' >> /tmp/sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> /tmp/sentinel.conf &&
      echo 'sentinel announce-hostnames yes' >> /tmp/sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 1' >> /tmp/sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 2000' >> /tmp/sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> /tmp/sentinel.conf &&
      redis-sentinel /tmp/sentinel.conf"

volumes:
  primary_data:
  replica_data:
  mongo_data:
  redis_master_data:
  redis_replica_data: