spring.application.name=sb-db-aspects-course
#spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_db
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/taxi_db
spring.datasource.primary.username=postgres
spring.datasource.primary.password=root
spring.datasource.replica.jdbc-url=jdbc:postgresql://localhost:5433/taxi_db
spring.datasource.replica.username=postgres
spring.datasource.replica.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.jooq.sql-dialect=Postgres
#debug=true
spring.mongodb.uri=mongodb://localhost:27018/taxi_mongo_db